#!/bin/sh

case "$1" in
    start)
        start-stop-daemon -n aesdsocket -S -x /usr/bin/aesdsocket -- -d
        ;;
    stop)
        start-stop-daemon -n aesdsocket -K
        ;;
    *)
        echo "aesd-start-stop {start|stop}"
        exit 1
        ;;
esac